### ISSUE TITLE
Discuss about the causality of nn.InstanceNorm1d and nn.InstanceNorm2d ?

### ISSUE THREAD

**Issue by vBaiCai** [Andong-Li-speech/GaGNet#2]
Hi, 

I find the GaGNet use InstanceNorm in these places:
https://github.com/Andong-Li-speech/GaGNet/blob/8a03b617b5bcf1a68342dc55ad462ddab97bbfc2/GaGNet.py#L359
https://github.com/Andong-Li-speech/GaGNet/blob/8a03b617b5bcf1a68342dc55ad462ddab97bbfc2/GaGNet.py#L290

For the InstanceNorm2d, the input shape is [batch, channel, num_frames, freq_feature_size], the mean and variance are calculated per [num_frames, freq_feature_size], which contain the all frames. So, the InstanceNorm2d seems to be non-causal.

**Comment by vBaiCai** [comment]
Same for InstanceNorm1d.

**Comment by Andong-Li-speech** [comment]
> Hi,
> 
> I find the GaGNet use InstanceNorm in these places:
> 
> https://github.com/Andong-Li-speech/GaGNet/blob/8a03b617b5bcf1a68342dc55ad462ddab97bbfc2/GaGNet.py#L359
> 
> 
> https://github.com/Andong-Li-speech/GaGNet/blob/8a03b617b5bcf1a68342dc55ad462ddab97bbfc2/GaGNet.py#L290
> 
> For the InstanceNorm2d, the input shape is [batch, channel, num_frames, freq_feature_size], the mean and variance are calculated per [num_frames, freq_feature_size], which contain the all frames. So, the InstanceNorm2d seems to be non-causal.

Thanks for your comment. Indeed in the training phase, the statistics about mean and variance for IN or BN are calculated among the whole spectrogram. However, they will be fixed in the inference phase. Although it is not straightly causal in the training phase, I think it is okay in the causal inference. Actually, you may as well replace 1-D(2-D) IN with LN or cumulative-style norm to see the performance and I am also looking forward to seeing the results : )

**Comment by vBaiCai** [comment]
By default, there is a little difference between IN and BN. BN uses the smoothed statistics during inference, but IN does not.

**Comment by vBaiCai** [comment]
BN or cumulative normalization will be a good choice.

By default, there is a little difference between IN and BN. BN uses the smoothed statistics during inference, but IN does not.

**Comment by vBaiCai** [comment]
BN or cumulative normalization will be a good choice.
By default, there is a little difference between IN and BN. BN uses the smoothed statistics during inference, but IN does not.

**Comment by vBaiCai** [comment]
Thanks for the reply. By default, there is a little difference between BN and IN. BN uses the smoothed statistics during inference, but IN does not. It's like you say, that BN, LN, and cumulative normalization can be good choices.
